name: Build & Test

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Build with ncc
      run: |
        npm install
        npm run build

    - name: Invoke echo 1 workflow using this action
      uses: ./
      with:
        workflow: Message Echo 1
        token: ${{ secrets.PERSONAL_TOKEN }}
        inputs: '{"message": "blah blah"}'

    - name: Invoke echo 2 workflow using this action
      uses: ./
      with:
        workflow: Message Echo 2
        token: ${{ secrets.PERSONAL_TOKEN }}

    - name: Invoke echo 1 workflow by id
      uses: ./
      with:
        workflow: '1854247'
        token: ${{ secrets.PERSONAL_TOKEN }}
        inputs: '{"message": "Mango jam"}'

    - name: Invoke workflow for SHA
      uses: ./
      with:
        workflow: Message Echo 1
        token: ${{ secrets.PERSONAL_TOKEN }}
        sha: ${{ github.sha }}
        inputs: '{"message": "SHA dispatch"}'

    - name: Error out invoking workflow by mismatched ref/SHA
      id: sha-invoke-error
      uses: ./
      with:
        workflow: Message Echo 1
        token: ${{ secrets.PERSONAL_TOKEN }}
        sha: "bad"
      continue-on-error: true

    - name: Check that mismatched ref/SHA errored out
      run: |
        [ ${{ steps.sha-invoke-error.outcome }} == "failure" ]

    - name: Update repo with build
      uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Invoke external workflow using this action
    #   uses: ./
    #   with:
    #     workflow: Deploy To Kubernetes           
    #     repo: benc-uk/dapr-store
    #     token: ${{ secrets.PERSONAL_TOKEN }}
    #     ref: master 
   